import db from "../models";

export const pessoas = [
  {
    usuario_id: 1,
    nome: "John Doe",
    email: "johndoe@example.com",
    rua: "Rua da Amizade",
    numero: "123",
    complemento: "Bloco B",
    bairro: "Centro",
    cidade: "São Paulo",
    estado: "AC",
    cpf: "121.111.111-21",
    datanascimento: "01/01/1980",
    telefone: "48415544075",
    dependentes: 2,
    estadocivil: "Solteiro(a)",
    genero: "Mulher",
    etnia: "Branco/Caucasiano",
    rendafamiliar: 600,
    telefonerecado: "222222",
    objetivo: "testando muito",
  },
  {
    usuario_id: 1,
    nome: "Jane Smith",
    email: "janesmith@example.com",
    rua: "Avenida das Flores",
    numero: "456",
    complemento: "",
    bairro: "Bela Vista",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    cpf: "987.654.321-00",
    datanascimento: "15/07/1995",
    telefone: "5544667788",
    dependentes: 1,
    estadocivil: "Casado(a)",
    genero: "Homem",
    etnia: "Negro/Afrodescendente",
    rendafamiliar: 1500,
    telefonerecado: "333333",
    objetivo: "Contribuir para a comunidade",
  },
  {
    usuario_id: 1,
    nome: "Maria Silva",
    email: "mariasilva@example.com",
    rua: "Rua das Palmeiras",
    numero: "789",
    complemento: "Apto 101",
    bairro: "Jardim Botânico",
    cidade: "Curitiba",
    estado: "PR",
    cpf: "555.111.222-33",
    datanascimento: "25/03/1990",
    telefone: "9988776655",
    dependentes: 0,
    estadocivil: "Divorciado(a)",
    genero: "Mulher",
    etnia: "Pardo/Mestiço",
    rendafamiliar: 2500,
    telefonerecado: "444444",
    objetivo: "Auxiliar pessoas em situação de vulnerabilidade"
  },
  {
    usuario_id: 4,
    nome: "Carlos Oliveira",
    email: "carlosoliveira@example.com",
    rua: "Av. Paulista",
    numero: "1000",
    complemento: "Sala 202",
    bairro: "Bela Vista",
    cidade: "São Paulo",
    estado: "SP",
    cpf: "777.888.999-00",
    datanascimento: "10/05/1985",
    telefone: "1122334455",
    dependentes: 3,
    estadocivil: "Casado(a)",
    genero: "Homem",
    etnia: "Amarelo/Asiático",
    rendafamiliar: 4000,
    telefonerecado: "555555",
    objetivo: "Promover educação e acesso à cultura"
  },
  {
    usuario_id: 1,
    nome: "Joana Costa",
    email: "joanacosta@example.com",
    rua: "Rua das Flores",
    numero: "987",
    complemento: "Apto 301",
    bairro: "Jardim Primavera",
    cidade: "Belo Horizonte",
    estado: "MG",
    cpf: "111.222.333-44",
    datanascimento: "12/08/1992",
    telefone: "9988776655",
    dependentes: 0,
    estadocivil: "Solteiro(a)",
    genero: "Mulher",
    etnia: "Branco/Caucasiano",
    rendafamiliar: 3500,
    telefonerecado: "666666",
    objetivo: "Contribuir para causas sociais"
  },
  {
    usuario_id: 1,
    nome: "Pedro Nunes",
    email: "pedronunes@example.com",
    rua: "Avenida Central",
    numero: "456",
    complemento: "",
    bairro: "Centro",
    cidade: "Fortaleza",
    estado: "CE",
    cpf: "555.666.777-88",
    datanascimento: "25/06/1987",
    telefone: "5544667788",
    dependentes: 2,
    estadocivil: "Casado(a)",
    genero: "Homem",
    etnia: "Negro/Afrodescendente",
    rendafamiliar: 2000,
    telefonerecado: "777777",
    objetivo: "Promover a igualdade de oportunidades"
  },
  {
    usuario_id: 1,
    nome: "Laura Almeida",
    email: "lauraalmeida@example.com",
    rua: "Rua das Palmeiras",
    numero: "321",
    complemento: "Bloco C",
    bairro: "Jardim Botânico",
    cidade: "Porto Alegre",
    estado: "RS",
    cpf: "999.888.777-66",
    datanascimento: "18/03/1991",
    telefone: "5544332211",
    dependentes: 1,
    estadocivil: "Casado(a)",
    genero: "Mulher",
    etnia: "Pardo/Mestiço",
    rendafamiliar: 2800,
    telefonerecado: "888888",
    objetivo: "Auxiliar crianças em situação de vulnerabilidade"
  },
  {
    usuario_id: 1,
    nome: "Rafael Lima",
    email: "rafaellima@example.com",
    rua: "Av. Central",
    numero: "123",
    complemento: "Sala 501",
    bairro: "Centro",
    cidade: "Recife",
    estado: "PE",
    cpf: "777.888.999-00",
    datanascimento: "05/09/1985",
    telefone: "1122334455",
    dependentes: 3,
    estadocivil: "Casado(a)",
    genero: "Homem",
    etnia: "Amarelo/Asiático",
    rendafamiliar: 4000,
    telefonerecado: "999999",
    objetivo: "Promover"
  }
];

export const seedPessoas = async () => {
  try {
    for (const pessoa of pessoas) {
      await db.Pessoa.create(pessoa);
    }
    console.log("Pessoas criados com sucesso.");
  } catch (err) {
    console.error(err);
  }
};
